# These two properties are always first, and always absolute paths
source: "/home/zachary/blog_converter"
destination: "/home/zachary/blog_converter/public"

post_dir: "posts"
page_dir: "pages"
image_dir: "images"
static_dir: "static"
tag_template: "templates/tag.mustache.html"
category_template: "templates/tag.mustache.html"
post_template: "templates/post.mustache.html"

post_destination: "{{destination}}/posts/{{id}}.html"
tag_destination: "{{destination}}/tag/{{tag}}.html"
category_destination: "{{destination}}/category/{{category}}.html"
page_destination: "{{destination}}/{{page}}"
image_destination: "{{destination}}/images/{{image}}"
static_destination: "{{destination}}/{{relative_path}}"
