# These two properties are always first, and always absolute paths
source: "/home/zachary/blog"
destination: "/home/zachary/blog/public"
web_root: "https://blog2.za3k.com"
domain: "blog2.za3k.com"
title: 'blog of zachary "za3k" vance'

post_dir: "posts"
comments_dir: "comments"
page_dir: "page"
image_dir: "images"
static_dir: "static"

author_template: "templates/author.mustache.html"
category_template: "templates/category.mustache.html"
deadlinks_template: "templates/deadlinks.mustache.html"
links_template: "templates/links.mustache.html"
index_template: "templates/index.mustache.html"
feed_template: "templates/feed.mustache.html"
layout_template: "templates/layout.mustache.html"
post_template: "templates/post.mustache.html"
postcombined_template: "templates/postcombined.mustache.html"
tag_template: "templates/tag.mustache.html"
tagcloud_template: "templates/tagcloud.mustache.html"

author_destination: "{{destination}}/author/{{slug}}.html"
category_destination: "{{destination}}/category/{{slug}}.html"
deadlinks_destination: "{{destination}}/page/deadlinks.html"
links_destination: "{{destination}}/page/links.html"
index_destination: "{{destination}}/page/index.html"
feed_destination: "{{destination}}/page/feed.xml"
image_destination: "{{destination}}/images/{{image}}"
page_destination: "{{destination}}/{{page}}"
post_destination: "{{destination}}/posts/{{id}}.html"
post_md_destination: "{{destination}}/posts/{{id}}.md.html"
post_html_destination: "{{destination}}/posts/{{id}}.orig.html"
static_destination: "{{destination}}/{{relative_path}}"
tag_destination: "{{destination}}/tag/{{slug}}.html"
